version: 2

sources:

  - name: aircall
    database: bluwalk-data-warehouse
    tables:
      - name: call_created
      - name: call_answered
      - name: call_ended
      - name: call_ringing_on_agent
  
  - name: aircall_v2
    database: bluwalk-data-warehouse
    tables:
      - name: call_created
      - name: call_answered
      - name: call_ended
      - name: call_ringing_on_agent
  
  - name: analytics_249934410
    database: bluwalk-data-warehouse
    tables:
      - name: events_*

  - name: analytics_323684004
    database: bluwalk-data-warehouse
    tables:
      - name: events_*

  - name: appmaker
    database: bluwalk-data-warehouse
    tables:
      - name: driver_ledger_table
      - name: driver_statement

  - name: bluwalk_website_prod
    database: bluwalk-data-warehouse
    tables:
      - name: account_created
      - name: application_submitted
      - name: nps_response_submitted

  - name: bolt
    database: bluwalk-data-warehouse
    tables:
      - name: daily_report_summary
      - name: daily_report_trips
      - name: driver_engagement
      - name: driver_performance
      - name: earnings_history
      - name: order_log
      - name: trips_history
  
  - name: bp
    database: bluwalk-data-warehouse
    tables:
      - name: invoice_transactions
      - name: transactions

  - name: correos
    database: bluwalk-data-warehouse
    tables:
      - name: correos_daily_report

  - name: drivfit
    database: bluwalk-data-warehouse
    tables:
      - name: customer_survey

  - name: facebook_ads
    database: bluwalk-data-warehouse
    tables:
      - name: insights
      - name: ads
  
  - name: free_now
    database: bluwalk-data-warehouse
    tables:
      - name: booking_history

  - name: gcloud
    database: bluwalk-data-warehouse
    tables:
      - name: cloudaudit_googleapis_com_data_access_*
  
  - name: generic
    database: bluwalk-data-warehouse
    tables:
      - name: calendar

  - name: google_ads
    database: bluwalk-data-warehouse
    tables:
      - name: campaign_performance_reports
  
  - name: google_workspace
    database: bluwalk-data-warehouse
    tables:
      - name: users

  - name: google_sheets
    database: bluwalk-data-warehouse
    tables:
      - name: user_own_vehicles
      - name: churn_prevention
      - name: uncollectible_recovery
      - name: fin_month_closing

  - name: hubspot
    database: bluwalk-data-warehouse
    tables:
      - name: contact
      - name: deal
      - name: deal_contact
      - name: deal_pipeline
      - name: deal_pipeline_stage
      - name: deal_stage
      - name: merged_deal
      - name: owner
      - name: owner_team
      - name: property
      - name: property_option
      - name: pipelines
      - name: team
      - name: team_user
      - name: ticket
      - name: ticket_contact
      - name: ticket_engagement
      - name: ticket_pipeline
      - name: ticket_pipeline_stage
      - name: users

  - name: mercadao
    database: bluwalk-data-warehouse
    tables:
      - name: account_status_log
      - name: daily_order_summary
      - name: training_schedule
      - name: order_log

  - name: monday
    database: bluwalk-data-warehouse
    tables:
      - name: issue_tracker_log

  - name: google_cloud_postgresql_public
    database: bluwalk-data-warehouse
    tables:
      - name: account_account
      - name: account_analytic_account
      - name: account_analytic_line
      - name: account_partial_reconcile
      - name: account_move_line
      - name: account_move
      - name: account_journal
      - name: account_payment
      - name: booking
      - name: close_period
      - name: fleet_vehicle
      - name: fleet_vehicle_insurance
      - name: fleet_vehicle_model
      - name: fleet_vehicle_model_brand
      - name: fuel
      - name: fuel_card_log
      - name: hr_employee
      - name: hr_department
      - name: ir_translation
      - name: product_product
      - name: product_template
      - name: product_category
      - name: rate_base
      - name: rental_contract
      - name: res_country_city
      - name: res_country
      - name: res_partner
      - name: res_sales_partner
      - name: res_sales_partner_type
      - name: res_sales_partner_account
      - name: res_sales_partner_account_log
      - name: res_users
      - name: sale_order
      - name: sale_order_line
      - name: segment
      - name: support_stage
      - name: support_ticket
      - name: support_ticket_category
      - name: support_ticket_theme
      - name: trips
      - name: vehicle_category
      - name: vehicle_rental

  - name: prio
    database: bluwalk-data-warehouse
    tables:
      - name: ev_transactions
      - name: invoice_transactions
      - name: ff_invoice_transactions
  
  - name: repsol
    database: bluwalk-data-warehouse
    tables:
      - name: invoice_transactions

  - name: talkdesk
    database: bluwalk-data-warehouse
    tables:
      - name: calls
      - name: flows

  - name: tracker_logs
    database: bluwalk-data-warehouse
    tables:
      - name: close_period_log

  - name: uber
    database: bluwalk-data-warehouse
    tables:
      - name: driver_activity
      - name: driver_status
      - name: trip_activity
      - name: driver_performance
      - name: driver_quality
      - name: payment_ledger
      - name: payments_order
      - name: payment_transactions

  - name: zendesk
    database: bluwalk-data-warehouse
    schema: zendesk
    description: "Status: Inactive. This source contains all Zendesk-related data, including support ticket information, user details, and satisfaction ratings."
    tables:
      - name: attachments
        description: "Contains metadata about file attachments within Zendesk tickets, such as content types, file names, and URLs."

      - name: group_memberships
        description: "Tracks associations between users and groups in Zendesk, detailing membership creation and updates."

      - name: groups
        description: "Details the groups created in Zendesk, including their names, creation, and update timestamps."

      - name: organizations
        description: "Lists all the organizations in Zendesk, along with related information like names, shared tickets, and comments."

      - name: satisfaction_ratings
        description: "Captures customer satisfaction ratings for tickets, including comments and the associated ticket and user IDs."

      - name: ticket_events
        description: "Logs ticket-related events, tracking status changes, assignments, tags, and satisfaction ratings."

      - name: ticket_fields
        description: "Defines custom fields within tickets, including descriptions, positions, and visibility settings."

      - name: ticket_forms
        description: "Stores Zendesk ticket form configurations, which determine the layout and fields of a ticket."

      - name: ticket_metrics
        description: "Records various metrics related to ticket handling and resolution, including wait times and resolution durations."

      - name: tickets
        description: "Main table containing tickets raised in Zendesk, their status, assignee, requester, and other key ticket details."

      - name: users
        description: "Contains details about users in Zendesk, including their roles, contact information, and activity status."